name: Check base image updated

on:
  workflow_dispatch:
#  schedule:
#    - cron: '0 6 * * *' # Runs daily at 6 AM UTC

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      needs-updating: ${{ steps.check.outputs.needs-updating }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Get base image from Containerfile
        id: get_base_image
        run: |
          base_image=$(grep -i '^FROM .* as production$' Containerfile | head -n1 | awk '{print $2}')
          echo "base-image=$base_image" >> $GITHUB_OUTPUT

      - name: Check if update available
        id: check
        uses: lucacome/docker-image-update-checker@v2.0.0
        with:
          base-image: ${{ steps.get_base_image.outputs.base-image }}
          image: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          platforms: linux/amd64,linux/arm64 # Use 'all' to check all platforms

  rebuild:
    needs: check
    if: needs.check.outputs.needs-updating == 'true'
    uses: ./.github/workflows/build-and-deploy.yml
    secrets: inherit