# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Cross-platform tests

on:
  workflow_dispatch:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    strategy:
      matrix:
        # https://docs.github.com/en/free-pro-team@latest/actions/reference/specifications-for-github-hosted-runners
        # ARM not yet supported on private repos - not even Pro
        # platform: [ubuntu-latest, ubuntu-24.04-arm, macos-latest, windows-latest]
        platform: [ubuntu-latest, macos-latest, windows-latest]
        node-version: [24.x]

    runs-on: ${{ matrix.platform }}

    permissions:
      contents: read
      actions: read
      checks: write
      pull-requests: write

    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - uses: actions/checkout@v3

      # deps
      - run: npm ci
      - run: npm run clean

      # tests
      - run: npm test:unit
      - name: Publish Test Report
        uses: scacap/action-surefire-report@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          check_name: Test report (${{ matrix.platform }}, ${{ matrix.node-version }})

      # e2e tests
      - name: Install playwright browsers
        run: npx playwright install --with-deps
      - run: npm test:e2e
