name: Test deployed website

# Controls when the workflow will run
on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *' # Runs daily at 3 AM UTC

jobs:
  all-tests:
    strategy:
      matrix: 
        platform:
          - ubuntu-latest
          # Disabled macos and windows.  Browsers should be identical, and we only build docker images for linux.
          # - macos-latest
          # - windows-latest
        node-version: [24.x]

    runs-on: ${{ matrix.platform }}

    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - uses: actions/checkout@v3

      # deps
      - run: npm ci

      # e2e tests
      - name: Install playwright browsers
        run: npx playwright install --with-deps
      - run: BASE_URL=https://jsonschemalint.com npm run test:e2e

      - name: Publish E2E Test Report
        uses: mikepenz/action-junit-report@v5
        if: success() || failure() # always run even if the previous step fails
        with:
          check_name: E2E test report (${{ matrix.platform }}, ${{ matrix.node-version }})
          report_paths: playwright-report/TEST-**.xml
          annotate_notice: true
